### ISSUE TITLE
Could you pls explain how to install this for non-Python-savvy users?

### ISSUE THREAD

**Issue by dmolin** [aravinda0/qtile-bonsai#1]
I've qtile installed through my distro package manager (pacman; I'm on Manjaro). That is, I haven't installed qtile from sources.
Not being a Python guy, I've no idea how to install qtile_tabbed; My distro refuses to run `pip install` in non managed environments and I've no idea how to approach this as a consequence. Is there a way to use your code in qtile without having to install qtile from sources or use `pip install`?

**Comment by aravinda0** [comment]
I'm on Manjaro too. Right now, the simple answer is that you'll need to do:

`pip install qtile-bonsai --break-system-packages` 

I'll update the README.

I have a TODO to publish this under linux distro package managers so you can install it the same way you do qtile.

The more pythonic way to do this would be to install `qtile` with [pipx](https://github.com/pypa/pipx) (which will set things up behind the scenes to use venvs), and then use `pipx inject` to install `qtile-bonsai` into the same generated venv as the one for qtile, so they can both 'see' each other.
