### ISSUE TITLE
Single Windows Margin, Border

### ISSUE THREAD

**Issue by gibranlp** [aravinda0/qtile-bonsai#10]
I could not find a way to set, the margin and border when there is a single window, and Bonsai does not respect the single parameters from qtile.

**Comment by aravinda0** [comment]
This is on master now. Scheduled for v0.4.

`window.single.margin`, `window.single.border_size` are the new options. Let me know if there are any issues!

**Comment by gibranlp** [comment]
Awesome thanks! will give it a try later today

Cheers
