### ISSUE TITLE
Fullscreen apps

### ISSUE THREAD

**Issue by gibranlp** [aravinda0/qtile-bonsai#11]
Another issue i have found is that when you have a few windows opened and lets say you have VLC on one of them and want to set the video full screen it doesnt work, it kinda fullscreens in its own window, if you only have 1 window it does work though.

![area_screenshot_3](https://github.com/user-attachments/assets/0c004ede-4c29-49c5-8879-60cd434451e5)

**Comment by aravinda0** [comment]
Confirmed.

**Comment by aravinda0** [comment]
I reckon this is handled now. Will test it in the wild for a bit.
