### ISSUE TITLE
New python version Bonsai not working

### ISSUE THREAD

**Issue by gibranlp** [aravinda0/qtile-bonsai#15]
hey man, i just updated my arch and now my qtile configuration is not working, because of qtile bonsai, saying it cant import, and when i try to update qtile bonsai i get this error:

```
pip install --upgrade qtile-bonsai --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python <3.13,>=3.10; 0.2.0 Requires-Python <3.13,>=3.10; 0.3.0 Requires-Python <3.13,>=3.10; 0.4.0 Requires-Python <3.13,>=3.10
ERROR: Could not find a version that satisfies the requirement qtile-bonsai (from versions: none)
ERROR: No matching distribution found for qtile-bonsai

```
not sure if i have to downgrade python or what to do.

Thanks in advance

**Comment by aravinda0** [comment]
@gibranlp A temp workaround could be to use `pip install qtile-bonsai --ignore-requires-python`

(The library itself is pretty self-contained - it just needs qtile. All the dependency resolution mess comes from the needs of CI/test environment)

**Comment by aravinda0** [comment]
The next release should install fine under Python 3.13. The above workaround is the way meanwhile.

Pending are some dev-only issues around CI env. I think there may be some wayland related blockers under Python 3.13 - eg. I can't seem to get pywlroots to build.
