### ISSUE TITLE
Disable Tabs

### ISSUE THREAD

**Issue by gibranlp** [aravinda0/qtile-bonsai#2]
Hello, first of all i think this a great addon to Qtile its massively changing the wayi use my WM and i have to  thank you for that.

I was wondering if there is a way to disable tabs, or at least to force only 1 tab per group. I already  have  a few groups and having tabs on top of groups feel like i need a few more keybindings.

I use a lot a "sticky window" that follows me throug groups, but when it comes into the Bonsai layout spanws as a tab, and then i  have to merge it to the the previous tab, this also happens when i send a window from a group to another they are sent as tabs instead of splits.

or maybe im doing the moves throug groups wrong, as i used to do it with the past layouts

Thanks  a lot 

*edit: i  added a bigger explanation.

**Comment by aravinda0** [comment]
Hey there.

So if I understand correctly, you only want to have splits and prevent the default behaviour of new windows being added as tabs?

There might be a way already by using the `window.default_add_mode` config option:
```
layouts = [
    Bonsai(**{
      "window.default_add_mode": "match_previous",
    }),
]
```

For the moment, the only two supported values are `tab` (default) and `match_previous`. `match_previous` will make it so if you opened a window as an x-split, then the next window will also open as an x-split.

One **caveat** right now is that for the very first window, it is considered as a 'tab', so the 'previous' would still mean 'tab' until you open your first split.

I considered allowing more options for `window.default_add_mode` - eg. `split_x` and `split_y`, but there are some nuances to consider (eg. split focused window? or add as top level splits? etc). I'll think on this some more.

Let me know if the workaround helps things a bit until the above is fleshed out.

**Comment by gibranlp** [comment]
Hey, thanks for the fast comment.

I have already added the "match_previous" mode, to some effect.

However on this i have noted a few things:

- when i start Qtile and I'm about to open the very first window, commands such as 
    - lazy.layout.spawn_split(terminal, "x")
    - lazy.layout.spawn_split(rofi_launcher, "x")
dont work, i have to open a terminal using the prompt and then i can launch another split terminal or another app through the rofi launcher.

Also when im using the rofi launcher, the position of the launched program is not where i intended to launch it, however if i launch a terminal with the split shortcut works fine.

![Screenshot_3](https://github.com/aravinda0/qtile-bonsai/assets/2806964/df31b314-c873-4c4f-b7a8-86caafd7af65)

In this image i had selected the right window with Github, and then openened the terminal with the keybind and openend fine in the right side.

![Screenshot_2](https://github.com/aravinda0/qtile-bonsai/assets/2806964/fd9fe905-c954-4813-875d-b5438bca1de0)

However if a have the right window selected and open a program in this case thunar through the rofi launcher it always opens on the left, or maybe this is intended.

Thanks a lot.

**Comment by aravinda0** [comment]
So there are two things in play here.

> when i start Qtile and I'm about to open the very first window or if i try to open the first window on any empty group, commands such as ... Don't work, i have to open a terminal or a program using the prompt and then i can launch another split terminal or another app through the rofi launcher.

Right. This is annoying as the underlying tree wants there to be a tab as the first construct. 
I've just pushed out a fix in 6318238 . That should let you trigger your `spawn_split()` binding for the very first window as well.

This will go out in the next release alongside some other things. But you can pip-install directly from the master branch to get this immediately.


> Also when im using the rofi launcher, the position of the launched program is not where i intended to launch it, however if i launch a terminal with the split shortcut works fine.

Yeah, I noticed this too sometimes. I'm fairly certain it's from how qtile handles mouse-based focus. Here's my attempt at explaining this:

- The [default qtile configuration](https://docs.qtile.org/en/latest/manual/config/index.html#default-configuration) has `follow_mouse_focus = True`. 
- When you invoke `spawn_split(rofi_cmd, "x")`, it will first trigger rofi's floating window to open (the Bonsai layout has now lost focus)
- If your mouse pointer was on the left side of the screen, when the rofi dialog closes, the existing left window immediately gets focus
- The new rofi-spawned program window becomes ready
- The new window is added to the Bonsai layout by splitting the currently focused window, which happens to be the left window now.

I guess one way to solve this would be to have `follow_mouse_focus = False` in your qtile config. Not sure if there are any non-hacky ways of solving this at the qtile-bonsai level without fighting qtile.

Let me know if that made sense.

**Comment by gibranlp** [comment]
Awesome i have updated to this branch now works flawless.

ANd about the ```Follow_mouse_focus``` i have checked now, i wont turn it into false but now i have a way to make the winodws  spawn where i want just moving the mouse.

Thanks a lot man, i will continue using Bonsai and if I find something else will let you know I this its a great project.

Cheers

**Comment by gibranlp** [comment]
Hello again, i was just wondering if it will be possible to disable tabs, in the future.

thanks.

**Comment by aravinda0** [comment]
I've extracted the relevant bits into #13. I think it ought to cover what you're looking for :)
