### ISSUE TITLE
tab_bar.tab.title_provider not called after window name change

### ISSUE THREAD

**Issue by saviola777** [aravinda0/qtile-bonsai#7]
When using a browser or other application which often changes its window title, the bonsai tab title does not update until switching tabs / groups. Probably needs the `client_name_updated` hook.

PS: Great layout! Loving the tabs as someone who is working exclusively with maximized windows.

**Comment by aravinda0** [comment]
Nice catch! I've handled this now, with the hook approach that you hinted at.

I didn't notice this since I was using the `BonsaiBar` in my setup and it seems qtile widgets are updated more generously by default.

**Comment by saviola777** [comment]
Thanks for the quick fix! For the me the `BonsaiBar` has the same issue though. 🤔

**Comment by aravinda0** [comment]
That's odd.

> You might have some widget(s) which change(s) width regularly which forces the whole bar to be redrawn?

I thought this would be it, but I just removed all my widgets and only kept `BonsaiBar`, but it still updates fine. I'm checking window-title changes in qutebrowser tabs and firefox tabs.

Are you noticing this with browser tabs, or some other application?

**Comment by aravinda0** [comment]
Oh never mind - brain fart. You were right - it was happening before, but it seems with the latest fix, the re-rendering of the layout also updates the bar, so things work now.

Can you try with the commit on master and see if it works for you?

**Comment by saviola777** [comment]
Ah, sorry, I should have tested that first! I'll see how I can get the git version of qtile-bonsai integrated into my qtile venv later and report back. 🫡

**Comment by saviola777** [comment]
Works! ✔️
