### ISSUE TITLE
Support tab.width auto for BonsaiBar

### ISSUE THREAD

**Issue by saviola777** [aravinda0/qtile-bonsai#8]
I'm trying to use the `BonsaiBar` as a replacement of the `WindowName` widget with `length = bar.STRETCH` and it would be great if the tabs would take up all the available space with `tab.width = "auto"` just like the tab bar of the layout does.

I could try my hand at a PR if you'd like, it doesn't seem that complicated at first glance, even for a qtile newbie like me.

**Comment by aravinda0** [comment]
Right, the widget should support this. I'll take a look at this later today!

**Comment by aravinda0** [comment]
This should be working now after https://github.com/aravinda0/qtile-bonsai/commit/22c80aa866e250cbf892cd7d437f6840f2b0e358

There were some nuances around these special bar values for widget length. I think I captured all of it, but if something seems amiss, please do comment.

If there are no issues for a day or so, I'll push out a v0.3 release.

**Comment by saviola777** [comment]
Works! ✔️ 

Thanks a lot.
